environment:
  nodejs_version: "6"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm i -g grunt
  - npm test
